<<<<<<< HEAD
# Generated by Django 3.2.25 on 2025-05-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subscription_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
=======
# Generated by Django 3.2.25 on 2025-05-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_subscription_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
>>>>>>> ba34c1e (Installed required apps)
