# Generated by Django 4.2.10 on 2025-09-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='date_subscribed',
            new_name='created_at',
        ),
    ]
