# Generated by Django 4.2.10 on 2025-09-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_date_subscribed_newslettersubscriber_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersubscriber',
            old_name='created_at',
            new_name='subscribed_at',
        ),
    ]
