# Generated by Django 4.2.10 on 2025-09-21 10:36

from django.db import migrations, models
import uuid

def generate_unique_tokens(apps, schema_editor):
    NewsletterSubscriber = apps.get_model('home', 'NewsletterSubscriber')
    for subscriber in NewsletterSubscriber.objects.all():
        subscriber.unsubscribe_token = uuid.uuid4()
        subscriber.save()

class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_created_at_newslettersubscriber_subscribed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RunPython(generate_unique_tokens),
    ]
