# Generated by Django 4.2.10 on 2025-09-21 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_newslettersubscriber_unsubscribe_token'),
    ]

    operations = [
    ]
