# Generated by Django 4.2.10 on 2025-09-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20250921_1143'),
        ('home', '0010_auto_20250921_1145'),
    ]

    operations = [
    ]
