# Generated by Django 4.2.10 on 2025-09-21 11:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_merge_0009_auto_20250921_1143_0010_auto_20250921_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
