# Generated by Django 4.2.10 on 2025-09-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_newslettersubscriber_unsubscribe_token'),
        ('home', '0013_add_unsubscribe_token'),
    ]

    operations = [
    ]
