# Generated by Django 4.2.10 on 2025-09-26 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0014_useragreement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragreement',
            name='accepted_on',
        ),
        migrations.AddField(
            model_name='useragreement',
            name='accepted_privacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useragreement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='useragreement',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='useragreement', to=settings.AUTH_USER_MODEL),
        ),
    ]
