# Generated by Django 4.2.10 on 2025-05-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='benefits',
            field=models.JSONField(default=list),
        ),
    ]
