# Generated by Django 4.2.21 on 2025-07-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_subscription_start_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('duration_days', models.IntegerField(default=30)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('features', models.TextField(help_text='Separate features with a line break')),
            ],
        ),
    ]
