# Generated by Django 4.2.21 on 2025-07-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stripe_price_id',
        ),
        migrations.AlterField(
            model_name='plan',
            name='features',
            field=models.TextField(help_text='Enter one feature per line'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
