# Generated by Django 3.2.25 on 2025-05-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20250507_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='classes',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
    ]
