# Generated by Django 4.2.21 on 2025-07-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_alter_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabledate',
            name='is_booked',
        ),
    ]
