# Generated by Django 4.2.10 on 2025-09-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_booking_booking_date_alter_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabledate',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
