# Generated by Django 4.2.21 on 2025-07-24 10:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_remove_availabledate_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
